autoCorrect: true
buildUponDefaultConfig: true

style:
  LongLine:
    enabled: true
    maximumLineLength: 120
  UnusedPrivateMember:
    enabled: true
  UnusedLocalVariable:
    enabled: true
  UnusedParameter:
    enabled: true

empty-blocks:
  EmptyFunctionBlock:
    enabled: true
  EmptyInitBlock:
    enabled: true
  EmptyClassBlock:
    enabled: true

imports:
  UnusedImports:
    enabled: true

complexity:
  MagicNumber:
    enabled: true

documentation:
  UndocumentedPublicClass:
    enabled: true
