name: Build, Test and Push

on:
  push:
    branches: [ develop ]

permissions: write-all

jobs:
  pipeline:
    runs-on: macos-latest
    env:
      ORG_GRADLE_PROJECT_buildWithoutApiKey: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run unit tests
        run: ./gradlew test

      - name: Run Android tests
        uses: reactivecircus/android-emulator-runner@v3
        with:
          api-level: 33
          arch: x86_64
          profile: pixel_5
          script: ./gradlew connectedCheck --stacktrace

      - name: Push to master branch
        if: ${{ success() }}
        uses: ad-m/github-push-action@master
        with:
          branch: master
          force: true