name: Build, Test and Push

on:
  push:
    branches: [ develop ]

permissions: write-all

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test

      - name: Set up Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          profile: Nexus 6
          script: echo "Generated AVD"

      - name: Stop ADB server
        run: adb kill-server

      - name: Start ADB server
        run: adb start-server

      - name: Wait for emulator/device to be ready
        run: |
          emulator_wait_counter=0
          until adb devices | grep -c "device" || [ $emulator_wait_counter -eq 10 ]; do
            echo "Waiting for emulator/device to be ready..."
            sleep 5
            ((emulator_wait_counter++))
          done
          adb devices

      - name: Run Android tests
        run: ./gradlew connectedCheck

      - name: Push to master branch
        if: ${{ success() }}
        uses: ad-m/github-push-action@master
        with:
          branch: master
          force: true